(function(b){function k(a,c){return parseInt(b.css(a[0],c))||0}b.fn.jCarouselLite=function(a){a=b.extend({carouselClass:"ul",indicatorClass:null,btnPrev:null,btnNext:null,btnGo:null,btnGoSelectClass:"active",mouseWheel:!1,auto:null,speed:200,easing:null,vertical:!1,circular:!0,visible:3,start:0,scroll:1,beforeStart:null,afterEnd:null},a||{});return this.each(function(){function c(c){if(!d){b.each(a.btnGo,function(c,f){b(f).removeClass(a.btnGoSelectClass)});a.beforeStart&&a.beforeStart.call(this,f.slice(g).slice(0,
e));if(a.circular)c<=a.start-e-1?(i.css(j,-((h-e*2)*n)+"px"),g=c==a.start-e-1?h-e*2-1:h-e*2-a.scroll,a.btnGo!=null&&(b(a.btnGo[g-1]).addClass(a.btnGoSelectClass),end=!1)):c>=h-e+1?(i.css(j,-(e*n)+"px"),g=c==h-e+1?e+1:e+a.scroll,a.btnGo!=null&&(b(a.btnGo[g-1]).addClass(a.btnGoSelectClass),end=!1)):(g=c,a.btnGo!=null&&(g==0?(b(a.btnGo[h-3]).addClass(a.btnGoSelectClass),b(a.btnGo[0]).removeClass(a.btnGoSelectClass),end=!1):g+1==h?(b(a.btnGo[0]).addClass(a.btnGoSelectClass),b(a.btnGo[h-3]).removeClass(a.btnGoSelectClass),
end=!0):(b(a.btnGo[g-1]).addClass(a.btnGoSelectClass),end=!1)));else if(c<0||c>h-e)return;else g=c;d=!0;i.animate(j=="left"?{left:-(g*n)}:{top:-(g*n)},a.speed,a.easing,function(){a.afterEnd&&a.afterEnd.call(this,f.slice(g).slice(0,e));d=!1});a.circular||(b(a.btnPrev+","+a.btnNext).removeClass("disabled"),b(g-a.scroll<0&&a.btnPrev||g+a.scroll>h-e&&a.btnNext||[]).addClass("disabled"))}return!1}var d=!1,j=a.vertical?"top":"left",o=a.vertical?"height":"width",l=b(this),i=b(a.carouselClass,l),m=b("li",
i),p=m.size(),e=a.visible;a.circular&&(i.prepend(m.slice(p-e-1+1).clone()).append(m.slice(0,e).clone()),a.start+=e);var f=b("li",i),h=f.size(),g=a.start;l.css("visibility","visible");var n=a.vertical?f[0].offsetHeight+k(f,"marginTop")+k(f,"marginBottom"):f[0].offsetWidth+k(f,"marginLeft")+k(f,"marginRight"),m=n*h,p=n*e;f.css({overflow:"hidden","float":a.vertical?"none":"left"});i.css({margin:"0",padding:"0",position:"relative","list-style-type":"none","z-index":"1"});l.css({overflow:"hidden",position:"absolute",
"z-index":"2",left:"0px"});f.css({width:f.width(),height:f.height()});i.css(o,m+"px").css(j,-(g*n));l.css(o,p+"px");a.btnPrev&&b(a.btnPrev).click(function(){clearInterval(a.carouselInterval);return c(g-a.scroll)});a.btnNext&&b(a.btnNext).click(function(){clearInterval(a.carouselInterval);return c(g+a.scroll)});b(document).keydown(function(e){if(a.circular){if(e.keyCode==a.keyNext)return clearInterval(a.carouselInterval),c(g+a.scroll);if(e.keyCode==a.keyPrev)return clearInterval(a.carouselInterval),
c(g-a.scroll)}else{if(e.keyCode==a.keyNext&&b(f[g+a.scroll]).size()>0)return clearInterval(a.carouselInterval),c(g+a.scroll);if(e.keyCode==a.keyPrev&&b(f[g-a.scroll]).size()>0)return clearInterval(a.carouselInterval),c(g-a.scroll)}});a.btnGo&&b.each(a.btnGo,function(e,f){b(f).click(function(){clearInterval(a.carouselInterval);return c(a.circular?a.visible+e:e)})});a.mouseWheel&&l.mousewheel&&l.mousewheel(function(b,e){clearInterval(a.carouselInterval);return e>0?c(g-a.scroll):c(g+a.scroll)});if(a.auto)a.carouselInterval=
setInterval(function(){c(g+a.scroll)},a.auto+a.speed)})}})(jQuery);
(function(b){b.fn.slideshow=function(k){var a={display_marker:!0};return this.each(function(){k&&b.extend(a,k);var c=b(this),d=c.find(".slideshow-slides li");if(d.size()>1){c.find(".control").show();c.hover(function(){c.find(".control").animate({opacity:1})}).mouseleave(function(){c.find(".control").animate({opacity:0.3})});var j=b('<div class="indicators" style="width:'+c.find(".slideshow-slides li").size()*18+'px;"></div>');d.each(function(a){a==0?j.append(b('<div class="indicator active">&nbsp;</div>')):
j.append(b('<div class="indicator">&nbsp;</div>'))});c.append(j);c.find(".slideshow-slides").jCarouselLite({indicatorClass:".indicators",circular:!0,btnNext:".next",btnPrev:".prev",btnGo:c.find(".indicators div.indicator"),speed:500,visible:1,auto:1E4})}d=c.find(".slideshow-slides li[data-url]");d.find(".block-link").height()<d.height()/2&&d.click(function(){event.preventDefault();document.location=b(this).attr("data-url")});d.addClass("pointer")})}})(jQuery);var GB;GB||(GB={});
GB.Taste.Newsletter=function(b){return{setup:function(){b.each(function(b,a){var c,d,j;c=$(a).find("form");GB.Usermeta.data();d=$(a).find("span.error_message");j=$(a).find("span.post_message");c.submit(function(){var a=$(this);$.ajax({url:"/api/v2/register_simple",data:a.serialize(),dataType:"json",success:function(b){b.success?(GB.Notify.publish("event/newsletter/signup"),a.fadeOut(500,function(){d.text("");d.fadeIn()})):b.msg[0].indexOf("Already Exists")<-1?a.fadeOut(500,function(){d.text("");
d.fadeIn()}):(j.fadeIn(),j.text("Thank you for subscribing."))},error:function(){}});$("#btn_join_newsletter").hide()})})}}};
(function(b){b.fn.gridfy=function(k){var a={};k&&b.extend(a,k);return this.each(function(){var a=b(this);b.each(a.children("div:not(.gridfied)"),function(a,c){var d=b(c),i={row:0,col:0};i.col=parseInt(d.attr("data-col")||1);i.row=parseInt(d.attr("data-row")||1);i.col>1&&d.innerWidth(d.innerWidth()*i.col+14*(i.col-1));i.row>1&&d.innerHeight(d.innerHeight()*i.row+15*(i.row-1));d.attr("data-url")&&d.addClass("pointer");d.addClass("gridfied")});var d=a.find("div.grid-cell[data-url]");d.find(".block-link").height()<
d.height()/2&&a.find("div.grid-cell[data-url]").click(function(a){a.preventDefault();document.location=b(this).attr("data-url")})})}})(jQuery);
(function(b){b.fn.hoverIntent=function(k,a){var c={sensitivity:7,interval:100,timeout:0},c=b.extend(c,a?{over:k,out:a}:k),d,j,o,l,i=function(a){d=a.pageX;j=a.pageY},m=function(a,f){f.hoverIntent_t=clearTimeout(f.hoverIntent_t);if(Math.abs(o-d)+Math.abs(l-j)<c.sensitivity)return b(f).unbind("mousemove",i),f.hoverIntent_s=1,c.over.apply(f,[a]);else o=d,l=j,f.hoverIntent_t=setTimeout(function(){m(a,f)},c.interval)},p=function(a){var d=jQuery.extend({},a),h=this;if(h.hoverIntent_t)h.hoverIntent_t=clearTimeout(h.hoverIntent_t);
if(a.type=="mouseenter"){if(o=d.pageX,l=d.pageY,b(h).bind("mousemove",i),h.hoverIntent_s!=1)h.hoverIntent_t=setTimeout(function(){m(d,h)},c.interval)}else if(b(h).unbind("mousemove",i),h.hoverIntent_s==1)h.hoverIntent_t=setTimeout(function(){h.hoverIntent_t=clearTimeout(h.hoverIntent_t);h.hoverIntent_s=0;c.out.apply(h,[d])},c.timeout)};return this.bind("mouseenter",p).bind("mouseleave",p)}})(jQuery);